  import type { Metadata } from "next";
  import { Ubuntu } from "next/font/google";
  import "./globals.css";

  const ubuntu = Ubuntu({
    variable: "--font-ubuntu",
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`${ubuntu.className} antialiased`}
        >
          {children}
        </body>
      </html>
    );
  }
